/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY (SEE 'scripts/format-images.js') */

const AVATARS = {
  'allan-munger': require('./avatars/allan-munger.png'),
  'amanda-brady': require('./avatars/amanda-brady.png'),
  'ashley-mc-carthy': require('./avatars/ashley-mc-carthy.png'),
  'carlos-slattery': require('./avatars/carlos-slattery.png'),
  'carole-poland': require('./avatars/carole-poland.png'),
  'cecil-folk': require('./avatars/cecil-folk.png'),
  'celeste-burton': require('./avatars/celeste-burton.png'),
  'charlotte-waltson': require('./avatars/charlotte-waltson.png'),
  'colin-ballinger': require('./avatars/colin-ballinger.png'),
  'daisy-phillips': require('./avatars/daisy-phillips.png'),
  'elliot-woodward': require('./avatars/elliot-woodward.png'),
  'elvia-atkins': require('./avatars/elvia-atkins.png'),
  'erik-nason': require('./avatars/erik-nason.png'),
  'henry-brill': require('./avatars/henry-brill.png'),
  'isaac-fielder': require('./avatars/isaac-fielder.png'),
  'johnie-mcconnell': require('./avatars/johnie-mcconnell.png'),
  'kat-larsson': require('./avatars/kat-larsson.png'),
  'katri-ahokas': require('./avatars/katri-ahokas.png'),
  'kevin-sturgis': require('./avatars/kevin-sturgis.png'),
  'kristin-patterson': require('./avatars/kristin-patterson.png'),
  'lydia-bauer': require('./avatars/lydia-bauer.png'),
  'mauricio-august': require('./avatars/mauricio-august.png'),
  'miguel-garcia': require('./avatars/miguel-garcia.png'),
  'mona-kane': require('./avatars/mona-kane.png'),
  'robert-tolbert': require('./avatars/robert-tolbert.png'),
  'robin-counts': require('./avatars/robin-counts.png'),
  'tim-deboer': require('./avatars/tim-deboer.png'),
  'wanda-howard': require('./avatars/wanda-howard.png'),
};

export default AVATARS;
